export { default as Home } from './Home'
export { default as Service } from './Service'
export { default as Portfolio } from './Portfolio'
export { default as Booking } from './Booking'
export { default as NotFound } from './NotFound'
